language: python
python:
    - 2.7
install: pip install pytest-dependency
before_script:
    - chmod +x .travis_install_neuron.sh
    - SRC_DIR=$HOME/local/src
    - NRN_INSTALL_DIR=$HOME/local/nrn
    - ./.travis_install_neuron.sh ${SRC_DIR} ${NRN_INSTALL_DIR}
    - export PATH=$PATH:${NRN_INSTALL_DIR}/x86_64/bin
    - export PYTHONPATH=$PYTHONPATH:${NRN_INSTALL_DIR}/lib/python
script: 
    - pytest -s -q --tb=no
    - make test
